### ISSUE TITLE
Example Sales Analytics : sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by yemaney** [totalhack/zillion#14]
Following the example tutorial from the docs, running into an error.

System:
Windows 10
Python3.11
qdrant docker-compose file being used

Code I ran:
```py
from zillion import Warehouse

wh = Warehouse(config="https://raw.githubusercontent.com/totalhack/zillion/master/examples/example_wh_config.json")
```
Error
```
No ZILLION_CONFIG specified, using default settings
Traceback (most recent call last):
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3366, in _wrap_pool_connect
    return fn()
           ^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 388, in __init__
    self.__connect()
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 690, in __connect
    with util.safe_reraise():
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yeman_s1h20q2\Yemane\zill\main.py", line 1, in <module>
    from zillion import Warehouse
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\zillion\__init__.py", line 21, in <module>
    from .datasource import DataSource
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\zillion\datasource.py", line 30, in <module>
    from zillion.field import (
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\zillion\field.py", line 18, in <module>
    from zillion.model import zillion_engine, DimensionValues
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\zillion\model.py", line 51, in <module>
    zillion_metadata.create_all(zillion_engine)
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 4930, in create_all
    bind._run_ddl_visitor(
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3232, in _run_ddl_visitor
    with self.begin() as conn:
         ^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3148, in begin
    conn = self.connect(close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3369, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2203, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3366, in _wrap_pool_connect
    return fn()
           ^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 388, in __init__
    self.__connect()
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 690, in __connect
    with util.safe_reraise():
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeman_s1h20q2\Yemane\zill\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by yemaney** [comment]
The issue seems to be around opening an SQLite db file. 
Am I supposed to create one, or is the library supposed to create it automatically...?

**Comment by totalhack** [comment]
It actually downloads the sqlite DB for you, that's what [this line](https://github.com/totalhack/zillion/blob/1050a1a6b3cd78b362851eb83085085e911fb49a/examples/example_wh_config.json#L50) in the config controls.

I'm wondering if this is just a windows thing, as I've only tested on Linux/Mac. You can see [here](https://github.com/totalhack/zillion/blob/master/zillion/core.py#L425) what zillion's default settings look like when no config is specified, which has paths that contain invalid slashes for windows:

```
        print("No ZILLION_CONFIG specified, using default settings")
        config = dict(
            DEBUG=False,
            LOG_LEVEL="WARNING",
            DB_URL="sqlite:////tmp/zillion.db",
            ADHOC_DATASOURCE_DIRECTORY="/tmp",
            LOAD_TABLE_CHUNK_SIZE=5000,
            OPENAI_API_KEY=None,
            OPENAI_MODEL="gpt-3.5-turbo",
            QDRANT_HOST=None,
            DATASOURCE_QUERY_MODE=DataSourceQueryModes.SEQUENTIAL,
            DATASOURCE_QUERY_TIMEOUT=None,
            DATASOURCE_CONTEXTS={},
        )
```

You can try overriding those settings by providing a config file for zillion or by using environment vars. A little more info [here](https://github.com/totalhack/zillion#zillion-configuration).

**Comment by yemaney** [comment]
Seems like it was a Windows issue. The problem went away when I ran this in a docker container.

**Comment by totalhack** [comment]
Thanks. I'll make a note in the readme about the default configuration using paths that are not Windows friendly.
